### PR TITLE
Replace compass

### PR DESCRIPTION
**Pull request by eddywashere**
- [x] adjust sprite mixins
- [x] thorough comparison between node sass vs ruby + compass

Hoping this optimizes the experience of getting canon up and running. Also, reduce dependencies for this project.

### CODE REVIEW

**Comment by brianhartsock** [comment]
awesome

**Comment by eddywashere** [comment]
For people using canon & dependent on ruby compass mixins, consider using a compass fallback, https://github.com/Igosuki/compass-mixins. This will greatly reduce the amount of change required to upgrade. 

`bower install compass-mixins`

add include paths

```
includePaths: ['./bower_components/compass-mixins/lib']
```

**Comment by eddywashere** [comment]
If anyone wants to give this a go, I added a branch to canon-bower at https://github.com/rackerlabs/canon-bower/tree/libsass

bower ex:

```
bower install canon#libsass --save
```

**Comment by eddywashere** [comment]
fyi, this works with ruby compass. Just be sure to update font/image paths in compass config and copy over the following files

```
## just an example of what copying should look like
['bower_components/canon/images/*.gif',
'bower_components/canon/images/*.png']: '/dist'


['bower_components/canon/fonts/*']: '/dist/fonts'
```

**Comment by bradgignac** [comment]
:shipit:

**Pull request merged**
