### PR TITLE
Gemfile: add jekyll

### PR DESCRIPTION
**Pull request by buhman**
There is a reference to this in `Gemfile.lock`, however this is not actually installed without it actually being present in the Gemfile, as it is not a dependency of any other gem.

### CODE REVIEW

**Comment by eddywashere** [comment]
It's part of the github-pages gem. Tucked away here: https://github.com/github/pages-gem/blob/master/lib/github-pages/dependencies.rb

If you're thinking about a jekyll upgrade, it would worth verifying the markdown parser handles the existing content correctly.

**Comment by buhman** [comment]
> It's part of the github-pages gem

I'm slightly confused--it doesn't seem like `github-pages` is installed during `script/bootstrap`.

**Comment by eddywashere** [comment]
It should be part of `bundle install` - https://github.com/rackerlabs/canon/blob/master/script/bootstrap#L91-L94. Unless something got untagged in rubygems. Is that not working for you?

**Comment by eddywashere** [comment]
@buhman if you'd like to chat about stuff I'm in #canon-dev on irc or #canon-bootstrap in rackspace slack.

**Comment by buhman** [comment]
> Is that not working for you?

Ahh. I figured it out:

```
    github-pages was resolved to 14, which depends on
      jekyll (= 1.4.3) was resolved to 1.4.3, which depends on
        safe_yaml (~> 0.9.7)
```

Due to #177, we need to upgrade jekyll as well.

**Pull request closed without merging**
